const fetch = require('node-fetch');
const { Octokit } = require('@octokit/rest');

/**
 * @workspace Automated Content Generation Pipeline
 *
 * Runs every 4 hours to:
 * 1. Generate fresh content using AI models
 * 2. Create new posts/features
 * 3. Push to GitHub automatically
 * 4. Trigger deployment
 *
 * Environment Variables:
 * - GITHUB_TOKEN: GitHub personal access token with repo access
 * - GROK_API_KEY: For content generation
 * - REPO_OWNER: GitHub username (e.g., LiTree89)
 * - REPO_NAME: Repository name (e.g., HomeBase-2.0)
 */

const CONTENT_TYPES = [
  {
    type: 'blog_post',
    prompt: 'Generate a 500-word SEO-optimized blog post about modern web development trends, AI integration, or tech monetization. Include keywords naturally.',
    path: 'apps/web/public/blog'
  },
  {
    type: 'social_snippet',
    prompt: 'Create an engaging social media post snippet about technology, AI, or web development. Make it viral-worthy with hashtags.',
    path: 'apps/web/public/social'
  },
  {
    type: 'feature_idea',
    prompt: 'Suggest a new revenue-generating feature for a web application. Include implementation strategy and monetization angle.',
    path: 'docs/feature-ideas'
  }
];

async function generateContent(prompt) {
  const apiKey = process.env.GROK_API_KEY;
  const response = await fetch('https://api.x.ai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      messages: [
        {
          role: 'system',
          content: 'You are a content creator focused on SEO optimization, engagement, and monetization. Generate high-quality, unique content.'
        },
        { role: 'user', content: prompt }
      ],
      model: 'grok-4-fast-reasoning',
      max_tokens: 2048,
      temperature: 0.9
    })
  });

  const data = await response.json();
  return data.choices[0].message.content;
}

async function pushToGitHub(octokit, content, filePath, commitMessage) {
  const owner = process.env.REPO_OWNER || 'LiTree89';
  const repo = process.env.REPO_NAME || 'HomeBase-2.0';
  const branch = 'main';

  try {
    // Get current file SHA if exists
    let sha;
    try {
      const { data } = await octokit.repos.getContent({
        owner,
        repo,
        path: filePath,
        ref: branch
      });
      sha = data.sha;
    } catch (err) {
      // File doesn't exist yet
    }

    // Create or update file
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: filePath,
      message: commitMessage,
      content: Buffer.from(content).toString('base64'),
      branch,
      sha
    });

    return true;
  } catch (error) {
    throw new Error(`GitHub push failed: ${error.message}`);
  }
}

// @debugger Main timer-triggered function
module.exports = async function (context) {
  context.log('[ContentGenerator] Starting automated content generation');

  const githubToken = process.env.GITHUB_TOKEN;
  if (!githubToken) {
    context.log.error('[ContentGenerator] GITHUB_TOKEN not configured');
    return;
  }

  const octokit = new Octokit({ auth: githubToken });
  const timestamp = new Date().toISOString().split('T')[0];
  const results = [];

  // Generate random content type
  const contentConfig = CONTENT_TYPES[Math.floor(Math.random() * CONTENT_TYPES.length)];
  context.log(`[ContentGenerator] Selected content type: ${contentConfig.type}`);

  try {
    // Generate content
    const content = await generateContent(contentConfig.prompt);
    context.log(`[ContentGenerator] Generated ${content.length} characters`);

    // Create filename
    const filename = `${contentConfig.type}-${timestamp}-${Date.now()}.md`;
    const filePath = `${contentConfig.path}/${filename}`;

    // Format as markdown
    const markdownContent = `---
generated: ${new Date().toISOString()}
type: ${contentConfig.type}
automated: true
---

# Auto-Generated Content

${content}

---
*This content was automatically generated by AI Orchestrator*
`;

    // Push to GitHub
    await pushToGitHub(
      octokit,
      markdownContent,
      filePath,
      `🤖 Auto-generated ${contentConfig.type} - ${timestamp}`
    );

    results.push({
      type: contentConfig.type,
      path: filePath,
      status: 'success',
      size: content.length
    });

    context.log(`[ContentGenerator] Successfully pushed to ${filePath}`);

  } catch (error) {
    context.log.error(`[ContentGenerator] Error: ${error.message}`);
    results.push({
      type: contentConfig.type,
      status: 'failed',
      error: error.message
    });
  }

  context.log('[ContentGenerator] Completed. Results:', JSON.stringify(results));
};
