services:
  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://localhost:7071/api

  api:
    build: ./api
    ports:
      - "7071:80"
    environment:
      - AzureWebJobsScriptRoot=/home/site/wwwroot
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
