name: Firebase Hosting CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Build project
        run: npm run build || echo "No build script defined"
        working-directory: ./

      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v15.1.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
