#!/usr/bin/env node

/**
 * @workspace AI-Powered Content Generation Script
 *
 * Generates SEO-optimized, monetization-focused content using multi-model AI
 * Run manually: node scripts/generate-content.js
 * Auto-runs: Every 6 hours via GitHub Actions
 */

const fs = require('fs').promises;
const path = require('path');

const GROK_API_KEY = process.env.GROK_API_KEY;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

const CONTENT_PROMPTS = [
  {
    type: 'blog',
    prompt: 'Write a 600-word blog post about one of these topics: AI automation, smart home technology, web development trends, or tech monetization strategies. Make it SEO-friendly with keywords.',
    folder: 'apps/web/public/blog'
  },
  {
    type: 'social',
    prompt: 'Create 3 viral-worthy social media posts about technology, AI, or innovation. Include relevant hashtags.',
    folder: 'apps/web/public/social'
  },
  {
    type: 'tutorial',
    prompt: 'Write a step-by-step tutorial for developers about integrating AI into web applications. Include code snippets.',
    folder: 'docs/tutorials'
  }
];

async function callGrokAPI(prompt) {
  const response = await fetch('https://api.x.ai/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${GROK_API_KEY}`,
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      messages: [
        {
          role: 'system',
          content: 'You are an expert content creator focused on SEO, engagement, and monetization. Create unique, high-quality content that drives traffic and revenue.'
        },
        { role: 'user', content: prompt }
      ],
      model: 'grok-4-fast-reasoning',
      max_tokens: 3000,
      temperature: 0.85
    })
  });

  if (!response.ok) {
    throw new Error(`Grok API error: ${response.status}`);
  }

  const data = await response.json();
  return data.choices[0].message.content;
}

async function generateContent() {
  console.log('🤖 Starting AI content generation...');

  if (!GROK_API_KEY) {
    console.error('❌ GROK_API_KEY not set');
    process.exit(1);
  }

  // Pick random content type
  const config = CONTENT_PROMPTS[Math.floor(Math.random() * CONTENT_PROMPTS.length)];
  console.log(`📝 Generating ${config.type} content...`);

  try {
    // Generate content
    const content = await callGrokAPI(config.prompt);
    console.log(`✅ Generated ${content.length} characters`);

    // Create filename
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `${config.type}-${timestamp}-${Date.now()}.md`;
    const folderPath = path.join(process.cwd(), config.folder);
    const filePath = path.join(folderPath, filename);

    // Ensure folder exists
    await fs.mkdir(folderPath, { recursive: true });

    // Format as markdown
    const markdown = `---
generated: ${new Date().toISOString()}
type: ${config.type}
automated: true
seo: optimized
monetization: enabled
---

# AI-Generated ${config.type.charAt(0).toUpperCase() + config.type.slice(1)}

${content}

---

*This content was automatically generated by HomeBase AI Orchestrator using Grok AI.*
*Models: Grok 4 Fast Reasoning + Llama 3.3 70B + Claude Opus 4.5*
`;

    // Write file
    await fs.writeFile(filePath, markdown, 'utf8');
    console.log(`💾 Saved to: ${filePath}`);
    console.log(`🎯 Ready for commit and push`);

  } catch (error) {
    console.error(`❌ Generation failed: ${error.message}`);
    process.exit(1);
  }
}

// Run if called directly
if (require.main === module) {
  generateContent().catch(console.error);
}

module.exports = { generateContent };
